# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Enable systemd user process
        run: |
          loginctl enable-linger $(whoami)
          sleep 1
      
      - name: Set XDG_RUNTIME_DIR
        run: echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV

      - name: install podman
        run: |
          set -x
          sudo apt-get remove -y podman docker-ce docker docker-engine docker.io containerd runc ||:
          curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$( lsb_release -rs )/Release.key | sudo apt-key add -
          echo  "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$( lsb_release -rs )/ /" | sudo tee /etc/apt/sources.list.d/podman.list /dev/null
          sudo apt-get update
          sudo apt-get install -y podman
          sudo apt autoremove -y
          sudo systemctl start podman
          systemctl --user enable --now podman.socket
          systemctl --user status podman.socket 

      - name: Set DOCKER_HOST
        run: echo "DOCKER_HOST=$XDG_RUNTIME_DIR/podman/podman.sock" >> $GITHUB_ENV

      - run: echo $DOCKER_HOST
      
      - name: run a simple Maven build using Testcontainers
        run: ./mvnw -B verify
        env:
          DOCKER_HOST: $XDG_RUNTIME_DIR/podman/podman.sock
          
